# Generated by Django 5.1.3 on 2024-12-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_programmer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('Numero_ficha', models.CharField(max_length=7)),
                ('Formacion', models.BooleanField(default=True)),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
    ]
