# Generated by Django 5.1.3 on 2024-12-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Stu',
        ),
    ]
